export const PROJECT_MANAGEMENTS = [
  [
    {
      id: 1,
      code: "3A-1",
      title: "Identify a project based on opportunities",
      description: "Project identified",
      assignee: "John Doe",
      startDate: "1 Jan '24",
      endDate: "31 Mar '24",
      progress: "100%",
      statusColor: "#90B2E7",
      markColor: "#8ECEAA",
    },
    {
      id: 6,
      code: "3A-6",
      title: "Assess strategic fit",
      description: "Project fits into strategy",
      assignee: "John Doe",
      startDate: "3 Apr '24",
      endDate: "30 Jun '24",
      progress: "100%",
      statusColor: "#90B2E7",
      markColor: "#F4A9AA",
    },
    {
      id: 10,
      code: "3A-10",
      title: "Justify studying opportunity",
      description: "Opportunity is viable",
      assignee: "John Doe",
      startDate: "13 Jul '24",
      endDate: "30 Sep '24",
      progress: "100%",
      statusColor: "#4F85D9",
      markColor: "#F4A9AA",
    },
    {
      id: 12,
      code: "3A-12",
      title: "Define project targets",
      description: "Project targets",
      assignee: "John Doe",
      startDate: "7 Oct '24",
      endDate: "31 Dec '24",
      progress: "100%",
      statusColor: "#4F85D9",
      markColor: "#E4C767",
    },
  ],
  [
    {
      id: 2,
      code: "3A-2",
      title: "Further development of project schedule",
      description: "Project schedule maintenance",
      assignee: "John Doe",
      startDate: "1 Nov '24",
      endDate: "31 Dec '24",
      progress: "100%",
      statusColor: "#90B2E7",
      markColor: "#F4A9AA",
    },
    {
      id: 7,
      code: "3A-7",
      title: "Preparation of the PSA draft",
      description: "PSA draft",
      assignee: "John Doe the Second",
      startDate: "24 Jun '24",
      endDate: "27 Feb '25",
      progress: "100%",
      statusColor: "#90B2E7",
      markColor: "#E4C767",
    },
    {
      id: 11,
      code: "3A-11",
      title: "Selecting project progress metrics",
      description: "Project metrics",
      assignee: "John Doe",
      startDate: "1 Mar '25",
      endDate: "30 Apr '25",
      progress: "100%",
      statusColor: "#4F85D9",
      markColor: "#8ECEAA",
    },
    {
      id: 13,
      code: "3A-13",
      title: "Stakeholder engagement regarding the project concept",
      description: "Stakeholder agreement letter",
      assignee: "John Doe the Second",
      startDate: "1 May '23",
      endDate: "30 Jun '25",
      progress: "100%",
      statusColor: "#4F85D9",
      markColor: "#8ECEAA",
    },
  ],
  [
    {
      id: 3,
      code: "3A-3",
      title: "Develop a Master project schedule",
      description: "Master project schedule",
      assignee: "John Doe",
      startDate: "1 Jul '25",
      endDate: "31 Aug '25",
      progress: "100%",
      statusColor: "#90B2E7",
      markColor: "#8ECEAA",
    },

    {
      id: 8,
      code: "3A-8",
      title: "FID preparation",
      description: "FID",
      assignee: "John Doe the Second",
      startDate: "24 Jun '24",
      endDate: "27 Feb '25",
      progress: "100%",
      statusColor: "#4F85D9",
      markColor: "#F4A9AA",
    },
  ],
  [
    {
      id: 4,
      code: "3A-4",
      title: "Project execution monitoring",
      description: "Project status report",
      assignee: "John Doe",
      startDate: "12 Sep '25",
      endDate: "31 Oct '25",
      progress: "100%",
      statusColor: "#90B2E7",
      markColor: "#E4C767",
    },
    {
      id: 9,
      code: "3A-9",
      title: "Plan for Operations phase development",
      description: "Phase development plan",
      assignee: "John Doe the Second",
      startDate: "18 Dec '25",
      endDate: "24 Dec '25",
      progress: "100%",
      statusColor: "#4F85D9",
      markColor: "#8ECEAA",
    },
  ],
  [
    {
      id: 5,
      code: "3A-5",
      title: "Plan close out activities for the project",
      description: "Project close out",
      assignee: "John Doe",
      startDate: "1 Jan '25",
      endDate: "24 Dec '25",
      progress: "100%",
      statusColor: "#90B2E7",
      markColor: "#8ECEAA",
    },
  ],
];
export const health_safety_environment = [
  [
    {
      id: 1,
      code: "3A-1",
      title: "Secure environmental permits for seismic activities",
      description: "Operational permit",
      assignee: "John Doe",
      startDate: "1 Jun '24",
      endDate: "31 Mar '24",
      progress: "100%",
      statusColor: "#4F85D9",
      markColor: "#E4C767",
    },
    {
      id: 6,
      code: "3A-6",
      title: "Identify HSE risks and challenges in the fields",
      description: "Risk report and analysis",
      assignee: "John Doe",
      startDate: "30 Apr '24",
      endDate: "30 Jun '24",
      progress: "100%",
      statusColor: "#4F85D9",
      markColor: "#8ECEAA",
    },
    {
      id: 8,
      code: "3A-8",
      title: "Introduce HSE procedures for the seismic works in the field",
      description: "Procedures established and monitored",
      assignee: "John Doe",
      startDate: "13 Jul '24",
      endDate: "30 Sep '24",
      progress: "100%",
      statusColor: "#4F85D9",
      markColor: "#8ECEAA",
    },
  ],
  [
    {
      id: 2,
      code: "3A-2",
      title:
        "Develop initial environmental management plans, select HSE management concept",
      description: "Plans determined and approved with stakeholders",
      assignee: "John Doe",
      startDate: "1 Nov '24",
      endDate: "31 Dec '24",
      progress: "100%",
      statusColor: "#4F85D9",
      markColor: "#F4A9AA",
    },
  ],
  [
    {
      id: 3,
      code: "3A-3",
      title: "Define HSE procedures for execution phases",
      description: "HSE procedures defined",
      assignee: "John Doe",
      startDate: "1 Jul '25",
      endDate: "31 Aug '25",
      progress: "100%",
      statusColor: "#4F85D9",
      markColor: "#E4C767",
    },
    {
      id: 7,
      code: "3A-7",
      title: "Obtain environmental approval for project from the agencies",
      description: "State approved project plans",
      assignee: "John Doe the Second",
      startDate: "24 Jun '24",
      endDate: "27 Feb '25",
      progress: "100%",
      statusColor: "#4F85D9",
      markColor: "#8ECEAA",
    },
  ],
  [
    {
      id: 4,
      code: "3A-4",
      title: "Maintain HSE during operations",
      description: "HSE compliance",
      assignee: "John Doe",
      startDate: "12 Sep '25",
      endDate: "31 Oct '25",
      progress: "100%",
      statusColor: "#4F85D9",
      markColor: "#8ECEAA",
    },
  ],
  [
    {
      id: 5,
      code: "3A-5",
      title: "Maintain HSE during operations",
      description: "HSE compliance",
      assignee: "John Doe the Second",
      startDate: "1 Jan '25",
      endDate: "24 Dec '25",
      progress: "100%",
      statusColor: "#4F85D9",
      markColor: "#8ECEAA",
    },
  ],
];
export const metrics = [
  { label: "On-Time Tasks Completion rate", value: "56%", color: "text-black" },
  { label: "Issue Resolution Time", value: "48h", color: "text-black" },
  { label: "Budget Variance", value: "-5%", color: "text-yellow-500" },
  { label: "Resource Utilisation", value: "75%", color: "text-black" },
  { label: "Approval Turnaround Time", value: "3%", color: "text-green-500" },
  { label: "Late Task Percentage", value: "10%", color: "text-red-500" },
];
export const meetings = [
  { title: "Project Kickoff Meeting", time: "12:00 - 13:00" },
  { title: "Catch-up with John", time: "13:30 - 14:00" },
  { title: "Risk Management Meeting", time: "15:00 - 16:00" },
];
export const users = [
  { name: "John Doe", score: 1 },
  { name: "John Doe the Second", score: 3 },
  { name: "John Souls", score: 4 },
];

export const kanbanSidebarConfig = {
  styleConfig: {
    backgroundColor: "#E8E8EC",
    iconBackground: "#F0F0F3",
    badgeColor: "#F4A9AA",
    borderColor: "#D9D9E0",
  },
  task: {
    title: "Task Name",
    heading: "Develop a Master Project Schedule",
    description_title: "Task description",
    description:
      "Developing a master project schedule involves organizing and structuring all aspects of the project into a cohesive timeline. It begins with defining the project’s goals and boundaries, ensuring clarity on what needs to be achieved. Tasks are then broken down into smaller activities, dependencies mapped, and resources allocated with realistic time estimates. The critical path is analyzed to identify the sequence of essential tasks, followed by a thorough review and approval process to finalize the schedule and align all stakeholders.",
  },
  projectDetails: [
    { label: "Planned Start Date", value: "19 June 2024" },
    { label: "Planned Finish Date", value: "8 August 2024" }, // Corrected inconsistency
    {
      label: "Preceding Task",
      value: "Stakeholder engagement regarding the project concept",
    },
    { label: "Outcome", value: "Master Project Schedule" },
    {
      label: "Outcome Description",
      value:
        "A master project schedule is a comprehensive plan outlining all tasks, timelines, and dependencies required to complete a project. It serves as a central reference for tracking progress, managing resources, and ensuring alignment among stakeholders.",
    },
    { label: "Responsible", value: "Framsys Admin" },
  ],
  metadata: {
    priorityBadge: {
      text: "Red",
      color: "#F4A9AA",
      textColor: "#FFF7F7",
    },
    taskCode: {
      text: "1A-1",
      borderColor: "#D9D9E0",
    },
  },
};

export const sidebarConfig = {
  styleConfig: {
    backgroundColor: "bg-transparent",
  },
  task: {
    title: "Project Name",
    heading: "Framsys Methodology - Framework",
    description_title: "Project description",
    description:
      "Framsys methodology is designed to streamline project delivery by integrating advanced frameworks that align with organisational goals. It emphasises a structured approach, ensuring clear visibility across all project stages and fostering collaboration among stakeholders. By leveraging intelligent tools and processes, Framsys enables teams to identify risks, allocate resources efficiently, and optimise workflows. The methodology is adaptable, allowing enterprises to scale solutions based on project complexity and requirements. With a focus on achieving measurable outcomes, Framsys transforms project management into a seamless and results-driven experience.",
  },
  projectDetails: [
    { label: "Planned Start Date", value: "1 January 2024" },
    { label: "Planned Finish Date", value: "23 March 2025" },
    { label: "Preceding Task", value: "Sample Task Name" },
    { label: "Outcome", value: "Sample Outcome Name" },
    {
      label: "Outcome Description",
      value:
        "Framsys methodology is designed to streamline project delivery by integrating advanced frameworks that align with organisational goals.",
    },
    { label: "Responsible", value: "John Doe" },
  ],
  metadata: {
    priorityBadge: {
      text: "Red",
      color: "#F4A9AA",
      textColor: "#FFF7F7",
    },
    taskCode: {
      text: "1A-1",
      borderColor: "#D9D9E0",
    },
  },
};

export const pendingTasks = [
  {
    id: 1,
    taskId: "3A-1-1",
    progress: "10%",
    title: "Define project scope and objectives",
    markColor: "#F4A9AA",
    assignedTo: "John Doe",
    startDate: "13 Jul '24",
    endDate: "30 Sep '24",
    completeProgress: "100%",
  },
];

export const progressTasks = [
  {
    id: 1,
    taskId: "3A-1-2",
    progress: "10%",
    title: "Identify tasks and dependencies",
    markColor: "#8ECEAA",
    assignedTo: "John Doe",
    startDate: "13 Jul '24",
    endDate: "30 Sep '24",
    completeProgress: "100%",
  },
  {
    id: 2,
    taskId: "3A-1-3",
    progress: "10%",
    title: "Break down tasks and map dependencies",
    markColor: "#8ECEAA",
    assignedTo: "John Doe",
    startDate: "24 Jun ‘24",
    endDate: " 27 Feb ‘25",
    completeProgress: "100%",
  },
  {
    id: 3,
    taskId: "3A-1-3",
    progress: "10%",
    title: "Perform critical path analysis",
    markColor: "#E4C767",
    assignedTo: "John Doe",
    startDate: "1 Jul '25",
    endDate: "31 Aug '25",
    completeProgress: "100%",
  },
];
export const completedTasks = [
  {
    id: 1,
    taskId: "3A-1-5",
    progress: "10%",
    title: "Conduct stakeholder review and approval",
    markColor: "#F4A9AA",
    assignedTo: "John Doe",
    startDate: "1 Jan '25 ",
    endDate: "24 Dec '25",
    completeProgress: "100%",
  },
];
export const sidebarData = {
  home: {
    name: "Field Development Project",
    description: "A Field Development Project is a comprehensive endeavour aimed at the systematic planning, design, and execution of improvements or expansions in a particular area or field. This may involve the exploration, extraction, or utilisation of resources, the implementation of new technologies or infrastructure...",
    status: "In Progress",
    state: "Behind Schedule",
    dates: {
      planned: { start: "1 January 2024", finish: "23 March 2025" },
      forecast: { start: "1 January 2024", finish: "23 March 2025" },
      actual: { start: "1 January 2024", finish: "23 March 2025" }
    },
    outcome: {
      title: "Project Outcome",
      description: "Field Development Project generates substantial increase in productivity, resulting in improved efficiency, higher output, and reduced costs, positively impacting the field's ..."
    },
    responsible: "John Doe",
    phases: ["Identify", "Select", "Define", "Execute", "Operate & Close"],
    projectAreas: [
      "Commercial & Marketing",
      "Economic & Finance",
      "Health, Safety & Environment",
      "Infrastructure, Facilities & Fabrication",
      "Operations Management",
      "Project Services",
      "Procurement, Contracts & Logistics",
      "Project Management",
      "Quality Assurance",
      "Subsurfaces"
    ]
  },
  kanban: { title: "About Link 1", path: "/about-1" },
};
