export const project_managements = [
  {
    id: 1,
    code: "3A-1",
    title: "Identify a project based on opportunities",
    description: "Project identified",
    assignee: "John Doe",
    startDate: "1 Jan '24",
    endDate: "31 Mar '24",
    progress: "100%",
    statusColor: "#4F85D9",
    markColor: "#8ECEAA",
  },
  {
    id: 2,
    code: "3A-2",
    title: "Further development of project schedule",
    description: "Project schedule maintenance",
    assignee: "John Doe",
    startDate: "1 Nov '24",
    endDate: "31 Dec '24",
    progress: "100%",
    statusColor: "#4F85D9",
    markColor: "#F4A9AA",
  },
  {
    id: 3,
    code: "3A-3",
    title: "Develop a Master project schedule",
    description: "Master project schedule",
    assignee: "John Doe",
    startDate: "1 Jul '25",
    endDate: "31 Aug '25",
    progress: "25%",
    statusColor: "#4F85D9",
    markColor: "#8ECEAA",
  },
  {
    id: 4,
    code: "3A-4",
    title: "Project execution monitoring",
    description: "Project status report",
    assignee: "John Doe",
    startDate: "12 Sep '25",
    endDate: "31 Oct '25",
    progress: "0%",
    statusColor: "#4F85D9",
    markColor: "#E4C767",
  },
  {
    id: 5,
    code: "3A-5",
    title: "Plan close out activities for the project",
    description: "Project close out",
    assignee: "John Doe",
    startDate: "1 Jan '25",
    endDate: "24 Dec '25",
    progress: "100%",
    statusColor: "#4F85D9",
    markColor: "#8ECEAA",
  },
  {
    id: 6,
    code: "3A-6",
    title: "Assess strategic fit",
    description: "Project fits into strategy",
    assignee: "John Doe",
    startDate: "3 Apr '24",
    endDate: "30 Jun '24",
    progress: "100%",
    statusColor: "#4F85D9",
    markColor: "#F4A9AA",
  },
  {
    id: 7,
    code: "3A-7",
    title: "Preparation of the PSA draft",
    description: "PSA draft",
    assignee: "John Doe the Second",
    startDate: "24 Jun '24",
    endDate: "27 Feb '25",
    progress: "100%",
    statusColor: "#4F85D9",
    markColor: "#E4C767",
  },
  {
    id: 8,
    code: "3A-8",
    title: "FID preparation",
    description: "FID",
    assignee: "John Doe the Second",
    startDate: "24 Jun '24",
    endDate: "27 Feb '25",
    progress: "40%",
    statusColor: "#4F85D9",
    markColor: "#F4A9AA",
  },
  {
    id: 9,
    code: "3A-9",
    title: "Plan for Operations phase development",
    description: "Phase development plan",
    assignee: "John Doe the Second",
    startDate: "18 Dec '25",
    endDate: "24 Dec '25",
    progress: "0%",
    statusColor: "#4F85D9",
    markColor: "#8ECEAA",
  },
  {
    id: 10,
    code: "3A-10",
    title: "Justify studying opportunity",
    description: "Opportunity is viable",
    assignee: "John Doe",
    startDate: "13 Jul '24",
    endDate: "30 Sep '24",
    progress: "100%",
    statusColor: "#4F85D9",
    markColor: "#F4A9AA",
  },
  {
    id: 11,
    code: "3A-11",
    title: "Selecting project progress metrics",
    description: "Project metrics",
    assignee: "John Doe",
    startDate: "1 Mar '25",
    endDate: "30 Apr '25",
    progress: "40%",
    statusColor: "#4F85D9",
    markColor: "#8ECEAA",
  },
  {
    id: 12,
    code: "3A-12",
    title: "Define project targets",
    description: "Project targets",
    assignee: "John Doe",
    startDate: "7 Oct '24",
    endDate: "31 Dec '24",
    progress: "100%",
    statusColor: "#4F85D9",
    markColor: "#E4C767",
  },
  {
    id: 13,
    code: "3A-13",
    title: "Stakeholder engagement regarding the project concept",
    description: "Stakeholder agreement letter",
    assignee: "John Doe the Second",
    startDate: "1 May '23",
    endDate: "30 Jun '25",
    progress: "100%",
    statusColor: "#4F85D9",
    markColor: "#8ECEAA",
  },
];
export const health_safety_environment = [
  {
    id: 1,
    code: "3A-1",
    title: "Secure environmental permits for seismic activities",
    description: "Operational permit",
    assignee: "John Doe",
    startDate: "1 Jun '24",
    endDate: "31 Mar '24",
    progress: "100%",
    statusColor: "#4F85D9",
    markColor: "#E4C767",
  },
  {
    id: 2,
    code: "3A-2",
    title: "Develop initial environmental management plans, select HSE management concept",
    description: "Plans determined and approved with stakeholders",
    assignee: "John Doe",
    startDate: "1 Nov '24",
    endDate: "31 Dec '24",
    progress: "100%",
    statusColor: "#4F85D9",
    markColor: "#F4A9AA",
  },
  {
    id: 3,
    code: "3A-3",
    title: "Define HSE procedures for execution phases",
    description: "HSE procedures defined",
    assignee: "John Doe",
    startDate: "1 Jul '25",
    endDate: "31 Aug '25",
    progress: "30%",
    statusColor: "#4F85D9",
    markColor: "#E4C767",
  },
  {
    id: 4,
    code: "3A-4",
    title: "Maintain HSE during operations",
    description: "HSE compliance",
    assignee: "John Doe",
    startDate: "12 Sep '25",
    endDate: "31 Oct '25",
    progress: "0%",
    statusColor: "#4F85D9",
    markColor: "#8ECEAA",
  },
  {
    id: 5,
    code: "3A-5",
    title: "Maintain HSE during operations",
    description: "HSE compliance",
    assignee: "John Doe the Second",
    startDate: "1 Jan '25",
    endDate: "24 Dec '25",
    progress: "0%",
    statusColor: "#4F85D9",
    markColor: "#8ECEAA",
  },
  {
    id: 6,
    code: "3A-6",
    title: "Identify HSE risks and challenges in the fields",
    description: "Risk report and analysis",
    assignee: "John Doe",
    startDate: "30 Apr '24",
    endDate: "30 Jun '24",
    progress: "100%",
    statusColor: "#4F85D9",
    markColor: "#8ECEAA",
  },
  {
    id: 7,
    code: "3A-7",
    title: "Obtain environmental approval for project from the agencies",
    description: "State approved project plans",
    assignee: "John Doe the Second",
    startDate: "24 Jun '24",
    endDate: "27 Feb '25",
    progress: "30%",
    statusColor: "#4F85D9",
    markColor: "#8ECEAA",
  },
  {
    id: 8,
    code: "3A-8",
    title: "Introduce HSE procedures for the seismic works in the field",
    description: "Procedures established and monitored",
    assignee: "John Doe",
    startDate: "13 Jul '24",
    endDate: "30 Sep '24",
    progress: "100%",
    statusColor: "#4F85D9",
    markColor: "#8ECEAA",
  },
];
